package com.dilatush.shedsolar;

/**
 * @author Tom Dilatush  tom@dilatush.com
 */
public enum Events {

    BATTERY_TEMPERATURE_SENSOR_UP,
    BATTERY_TEMPERATURE_SENSOR_DOWN,
    HEATER_TEMPERATURE_SENSOR_UP,
    HEATER_TEMPERATURE_SENSOR_DOWN,
    CPO_DOWN,
    WEATHER_REPORT_MISSED,
    INTERNET_DOWN,
    INTERNET_UP,
    POSSIBLE_SSR_FAILURE,
    POSSIBLE_HEATER_FAILURE,
    POSSIBLE_SENSE_RELAY_FAILURE,
    NO_TEMPERATURE_OUTSIDE_THE_BOX,
    POSSIBLE_SSR_OR_SENSE_RELAY_FAILURE
}
